export const INITIAL_LOAD = 'HOLIDAYS/INITIAL_LOAD';
export const ADD_HOLIDAY = 'HOLIDAYS/ADD_HOLIDAY';
export const ADD_STAFF_MEMBER = 'HOLIDAYS/ADD_STAFF_MEMBER';
export const CALCULATE_HOLIDAYS = 'HOLIDAYS/CALCULATE_HOLIDAYS';
export const CALCULATE_STAFF_MEMBERS = 'HOLIDAYS/CALCULATE_STAFF_MEMBERS';
