export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const UPDATE_SECURITY_ROTA_WEEKLY_DAY =
  'UPDATE_SECURITY_ROTA_WEEKLY_DAY';
export const UPDATE_SECURITY_ROTA_WEEKLY_DAY_START =
  'UPDATE_SECURITY_ROTA_WEEKLY_DAY_START';
export const UPDATE_SECURITY_ROTA_WEEKLY_DAY_END =
  'UPDATE_SECURITY_ROTA_WEEKLY_DAY_END';
