export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const CHANGE_WEEK_DAY = 'CHANGE_WEEK_DAY';
export const SELECT_VENUE = 'SELECT_VENUE';
export const REJECT_SECURITY_SHIFT_REQUEST = 'REJECT_SECURITY_SHIFT_REQUEST';
