export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const CHANGE_WEEK_DAY = 'CHANGE_WEEK_DAY';
export const SELECT_VENUE = 'SELECT_VENUE';
export const SET_ASSIGNING_SHIFT_REQUEST = 'SET_ASSIGNING_SHIFT_REQUEST';
export const REJECT_SECURITY_SHIFT_REQUEST = 'REJECT_SECURITY_SHIFT_REQUEST';
export const REMOVE_SECURITY_SHIFT_REQUEST = 'REMOVE_SECURITY_SHIFT_REQUEST'; 
export const ADD_ROTA_SHIFT = 'ADD_ROTA_SHIFT'; 
export const ADD_ROTA = 'ADD_ROTA';
export const SHOW_GRAPH_DETAILS = 'SHOW_GRAPH_DETAILS';
export const CLOSE_GRAPH_DETAILS = 'CLOSE_GRAPH_DETAILS';

