export const INITIAL_LOAD = 'SHOW/INITIAL_LOAD';
export const UPDATE_INCIDENT_REPORT = 'SHOW/UPDATE_INCIDENT_REPORT';
export const EDIT_INCIDENT_REPORT = 'SHOW/EDIT_INCIDENT_REPORT';
export const SHOW_EDIT_REPORT = 'SHOW/SHOW_EDIT_REPORT';
export const HIDE_EDIT_REPORT = 'SHOW/HIDE_EDIT_REPORT';
export const DISABLE_REPORT = 'SHOW/DISABLE_REPORT';
