export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const MARK_REPORTS_COMPLETED = 'MARK_REPORTS_COMPLETED';
export const SET_REPORT_STATUS_DONE = 'SET_REPORT_STATUS_DONE';
export const CHANGE_PAY_RATE_FILTER = 'CHANGE_PAY_RATE_FILTER';

