export const INITIAL_LOAD = 'HOLIDAYS/INITIAL_LOAD';
export const UPDATE_AVATAR = 'HOLIDAYS/UPDATE_AVATAR';
export const ADD_NEW_HOLIDAY = 'HOLIDAYS/ADD_NEW_HOLIDAY';
export const CANCEL_ADD_NEW_HOLIDAY = 'HOLIDAYS/CANCEL_ADD_NEW_HOLIDAY';
