export const GLOBAL_ERROR_HAPPENED = 'GLOBAL_ERROR_HAPPENED';

export const COMPLETED_STEPS_CHANGED = 'COMPLETED_STEPS_CHANGED';

export const CHANGING_CURRENT_STEP = 'CHANGING_CURRENT_STEP';
export const CURRENT_STEP_CHANGED = 'CURRENT_STEP_CHANGED';

export const IS_ALL_STEPS_PASSED_CHANGED = 'IS_ALL_STEPS_PASSED_CHANGED';

export const ACCESS_TOKEN_CHANGED = 'ACCESS_TOKEN_CHANGED';

export const VENUE_VALUES_CHANGED = 'VENUE_VALUES_CHANGED';

export const PAYRATES_CHANGED = 'PAYRATES_CHANGED';

export const STAFF_TYPES_CHANGED = 'STAFF_TYPES_CHANGED';

export const GENDER_VALUES_CHANGED = 'GENDER_VALUES_CHANGED';

export const BASIC_INFORMATION_BLOCK_VALIDATED = 'BASIC_INFORMATION_BLOCK_VALIDATED';

export const AVATAR_BLOCK_VALIDATED = 'AVATAR_BLOCK_VALIDATED';

export const CONTACT_DETAILS_BLOCK_VALIDATED = 'CONTACT_DETAILS_BLOCK_VALIDATED';

export const VENUES_INFO_BLOCK_VALIDATED = 'VENUES_INFO_BLOCK_VALIDATED';

export const WORK_INFO_BLOCK_VALIDATED = 'WORK_INFO_BLOCK_VALIDATED';

export const AVATAR_PREVIEW_CHANGED = 'AVATAR_PREVIEW_CHANGED';

export const STEPPING_BACK_REGISTRATION = 'STEPPING_BACK_REGISTRATION';

export const ADDING_SOURCE_IMAGE = 'ADDING_SOURCE_IMAGE';

export const VALIDATING_ALL_ADD_STAFF_MEMBER_STEP_FORMS = 'VALIDATING_ALL_ADD_STAFF_MEMBER_STEP_FORMS';

export const REQUESTING_STAFF_MEMBER_SAVE = 'REQUESTING_STAFF_MEMBER_SAVE';
export const REQUESTING_STAFF_MEMBER_SAVE_FAILED = 'REQUESTING_STAFF_MEMBER_SAVE_FAILED';
export const REQUESTING_STAFF_MEMBER_SAVE_SUCCEEDED = 'REQUESTING_STAFF_MEMBER_SAVE_SUCCEEDED';
export const PENDING_STAFF_MEMBER_SAVE = 'PENDING_STAFF_MEMBER_SAVE';
