export const GLOBAL_ERROR_HAPPENED = 'GLOBAL_ERROR_HAPPENED';

export const COMPLETED_STEPS_CHANGED = 'COMPLETED_STEPS_CHANGED';

export const CHANGING_STEP_INFO = 'CHANGING_STEP_INFO';

export const STEPS_INFO_CHANGED = 'STEPS_INFO_CHANGED';

export const CHANGING_CURRENT_STEP = 'CHANGING_CURRENT_STEP';

export const CHANGE_TO = 'CHANGE_TO';

export const IS_ALL_STEPS_PASSED_CHANGED = 'IS_ALL_STEPS_PASSED_CHANGED';

export const ACCESS_TOKEN_CHANGED = 'ACCESS_TOKEN_CHANGED';

export const VENUES_CHANGED = 'VENUES_CHANGED';

export const PAY_RATES_CHANGED = 'PAY_RATES_CHANGED';

export const STAFF_TYPES_CHANGED = 'STAFF_TYPES_CHANGED';

export const GENDER_VALUES_CHANGED = 'GENDER_VALUES_CHANGED';

export const BASIC_INFORMATION_BLOCK_VALIDATED = 'BASIC_INFORMATION_BLOCK_VALIDATED';

export const AVATAR_BLOCK_VALIDATED = 'AVATAR_BLOCK_VALIDATED';

export const CONTACT_DETAILS_BLOCK_VALIDATED = 'CONTACT_DETAILS_BLOCK_VALIDATED';

export const VENUES_INFO_BLOCK_VALIDATED = 'VENUES_INFO_BLOCK_VALIDATED';

export const WORK_INFO_BLOCK_VALIDATED = 'WORK_INFO_BLOCK_VALIDATED';

export const AVATAR_PREVIEW_CHANGED = 'AVATAR_PREVIEW_CHANGED';

export const STEPPING_BACK_REGISTRATION = 'STEPPING_BACK_REGISTRATION';

export const ADDING_SOURCE_IMAGE = 'ADDING_SOURCE_IMAGE';

export const VALIDATING_ALL_ADD_STAFF_MEMBER_STEP_FORMS = 'VALIDATING_ALL_ADD_STAFF_MEMBER_STEP_FORMS';

export const REQUESTING_STAFF_MEMBER_SAVE = 'REQUESTING_STAFF_MEMBER_SAVE';
export const REQUESTING_STAFF_MEMBER_SAVE_FAILED = 'REQUESTING_STAFF_MEMBER_SAVE_FAILED';
export const REQUESTING_STAFF_MEMBER_SAVE_SUCCEEDED = 'REQUESTING_STAFF_MEMBER_SAVE_SUCCEEDED';
export const PENDING_STAFF_MEMBER_SAVE = 'PENDING_STAFF_MEMBER_SAVE';


export const REQUESTING_FLAGGED_STAFF_MEMBERS = 'REQUESTING_FLAGGED_STAFF_MEMBERS';
export const FLAGGED_STAFF_MEMBERS = 'FLAGGED_STAFF_MEMBERS';
export const TOGGLE_STAFF_MEMBER = 'staff_members/TOGGLE_STAFF_MEMBER';
export const FILL_FLAGGED_REQUEST_FIELDS = 'FILL_FLAGGED_REQUEST_FIELDS';
export const VALIDATE_PREVIOUS_FORM = 'VALIDATE_PREVIOUS_FORM';
export const SAVE_REVIEWED_MEMBER = 'SAVE_REVIEWED_MEMBER';
export const REMOVE_REVIEWED_MEMBER = 'REMOVE_REVIEWED_MEMBER';
export const SAVE_STAFF_MEMBER_ERROR_HAPPENED = 'staff_member/SAVE_STAFF_MEMBER_ERROR_HAPPENED';
export const CLEAR_ERRORS = 'global/CLEAR_ERRORS';
export const PENDING_REQUEST = 'global/PENDING_REQUEST';

export const SHOW_REVIEWED = 'SHOW_REVIEWED';
export const HIDE_REVIEWED = 'HIDE_REVIEWED';
export const TOGGLE_REVIEWED = 'TOGGLE_REVIEWED';
