export default {
  INITIAL_LOAD: 'INITIAL_LOAD',
  SET_ANSWER: 'SET_ANSWER',
  SAVE_ANSWERS: 'SAVE_ANSWERS',
  SAVE_ANSWERS_REQUEST: 'SAVE_ANSWERS_REQUEST',
  SAVE_ANSWERS_RECEIVE: 'SAVE_ANSWERS_RECEIVE',
  SAVE_ANSWERS_FAILURE: 'SAVE_ANSWERS_FAILURE'
};
