export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const SET_INITIAL_FILTERS = 'SET_INITIAL_FILTERS';
export const CHANGE_ROLE_FILTER = 'CHANGE_ROLE_FILTER';
export const CHANGE_STATUS_FILTER = 'CHANGE_STATUS_FILTER';

export const UPDATE_INVITE = 'UPDATE_INVITE';
