/*
Action types work a bit differently from the standard redux way.

The main reason is that most action types are generated by
createApiRequestAction, rather than hardcoded in advance.

We retain the ability to check that we don't use the wrong
action string by checking it exists in makeReducer.
*/

var typeStrings = [    
    "SHOW_CONFIRMATION_MODAL",
    "CANCEL_CONFIRMATION_MODAL",
    "COMPLETE_CONFIRMATION_MODAL",

    "CLOCK_IN_OUT_APP_SELECT_STAFF_TYPE",
    "SET_API_KEY",
    "SHOW_USER_ACTION_CONFIRMATION_MESSAGE",
    "HIDE_USER_ACTION_CONFIRMATION_MESSAGE",
    "REPLACE_WEEKLY_ROTA_FORECAST",
    "GENERIC_REPLACE_ALL_ITEMS",
    "SET_PAGE_OPTIONS",

    "API_REQUEST_START",
    "API_REQUEST_END",
    "SET_COMPONENT_ERROR"
    // plus ones added using registerActionType
]

var types = {};
typeStrings.forEach(function(typeString){
    types[typeString] = typeString;
})

export default types;

export function registerActionType(typeString){
    types[typeString] = typeString;
}
