import {
    clockInOutAppEnterUserMode,
    updateStaffStatus,
    enterUserModeWithConfirmation,
    clockInOutAppSelectStaffType,
    updateStaffStatusWithConfirmation,
    clockInOutAppFetchAppData
} from "./clocking"
export {
    clockInOutAppEnterUserMode,
    updateStaffStatus,
    clockInOutAppSelectStaffType,
    enterUserModeWithConfirmation,
    updateStaffStatusWithConfirmation,
    clockInOutAppFetchAppData
}

import {
    updateRotaStatus,
    publishRotas
} from "./rotas"
export {
    updateRotaStatus,
    publishRotas
}

import {
    showUserActionConfirmationMessage,
    hideUserActionConfirmationMessage
} from "./user-action-confirmation-messages"
export {
    showUserActionConfirmationMessage,
    hideUserActionConfirmationMessage
}

import {
    replaceWeeklyRotaForecast,
    updateRotaForecast,
    fetchWeeklyRotaForecast
} from "./rota-forecasts"
export {
    replaceWeeklyRotaForecast,
    updateRotaForecast,
    fetchWeeklyRotaForecast
}

import {
    showConfirmationModal,
    cancelConfirmationModal,
    completeConfirmationModal
} from "./confirmation-modal"
export {
    showConfirmationModal,
    cancelConfirmationModal,
    completeConfirmationModal
};

import {
    addRotaShift,
    updateRotaShift,
    deleteRotaShift
} from "./shifts"
export {
    addRotaShift,
    updateRotaShift,
    deleteRotaShift
}

import {
    setApiKey,
    setPageOptions
} from "./misc"
export {
    setApiKey,
    setPageOptions
}

import {
    loadInitialRotaAppState,
    loadInitalStaffTypeRotaAppState,
    loadInitialRotaOverviewAppState,
    loadInitialHoursConfirmationAppState
} from "./app-data"
export {
    loadInitialRotaAppState,
    loadInitalStaffTypeRotaAppState,
    loadInitialRotaOverviewAppState,
    loadInitialHoursConfirmationAppState
}

import {
    updateStaffMemberPinWithEntryModal,
    updateStaffMemberPin
} from "./staff-members"
export {
    updateStaffMemberPinWithEntryModal,
    updateStaffMemberPin
}

import {
    updateClockInBreak
} from "./clock-in-breaks"
export {
    updateClockInBreak
}

var actionCreators = {};

export function registerActionCreator(name, fn){
    if (actionCreators[name] !== undefined) {
        throw Error("Action creator " + name + " already existss")
    }
    actionCreators[name] = fn;
}


export default actionCreators;




/*
Action types work a bit differently from the standard redux way.

The main reason is that most action types are generated by
createApiRequestAction, rather than hardcoded in advance.

We retain the ability to check that we don't use the wrong
action string by checking it exists in makeReducer.
*/

var typeStrings = [
    "SHOW_CONFIRMATION_MODAL",
    "CANCEL_CONFIRMATION_MODAL",
    "COMPLETE_CONFIRMATION_MODAL",

    "CLOCK_IN_OUT_APP_SELECT_STAFF_TYPE",
    "SET_API_KEY",
    "SHOW_USER_ACTION_CONFIRMATION_MESSAGE",
    "HIDE_USER_ACTION_CONFIRMATION_MESSAGE",
    "REPLACE_WEEKLY_ROTA_FORECAST",
    "SET_PAGE_OPTIONS",

    "API_REQUEST_START",
    "API_REQUEST_END",
    "SET_COMPONENT_ERROR"
    // plus ones added using registerActionType
]

var actionTypes;
typeStrings.forEach(function(typeString){
    actionTypes[typeString] = typeString;
})

export {actionTypes}

export function registerActionType(typeString){
    if (!actionTypes) {
        actionTypes = {};
    }
    actionTypes[typeString] = typeString;
}

window.debug = window.debug || {};
window.debug.actionCreators = actionCreators
window.debug.actionTypes = actionTypes;
