export const FINANCE_REPORT_STATUS_DONE_STATUS = 'done';
export const FINANCE_REPORT_SHOW_ALL_FILTER_TYPE = 'show_all';
export const FINANCE_REPORT_SALARY_ONLY_FILTER_TYPE = 'salary_only';
export const FINANCE_REPORT_WITH_OWED_HOURS_FILTER_TYPE = 'with_owed_hours';
export const FINANCE_REPORT_WITH_HOLIDAYS_FILTER_TYPE = 'with_holidays';
export const FINANCE_REPORT_WITH_ACCESSORIES_FILTER_TYPE = 'with_accessories';

export const FILTER_TABS = [
  FINANCE_REPORT_WITH_ACCESSORIES_FILTER_TYPE,
  FINANCE_REPORT_WITH_HOLIDAYS_FILTER_TYPE,
  FINANCE_REPORT_WITH_OWED_HOURS_FILTER_TYPE,
  FINANCE_REPORT_SALARY_ONLY_FILTER_TYPE,
  FINANCE_REPORT_SHOW_ALL_FILTER_TYPE,
];

export const FILTER_TITLES = {
  [FINANCE_REPORT_SHOW_ALL_FILTER_TYPE]: 'Show All',
  [FINANCE_REPORT_SALARY_ONLY_FILTER_TYPE]: 'Salary Only',
  [FINANCE_REPORT_WITH_OWED_HOURS_FILTER_TYPE]: 'Owed Hours Only',
  [FINANCE_REPORT_WITH_HOLIDAYS_FILTER_TYPE]: 'Paid Holidays Only',
  [FINANCE_REPORT_WITH_ACCESSORIES_FILTER_TYPE]: 'Accessories Only',
};
