export const INITIAL_LOAD = 'LOAD_INITIAL_DATA';
export const UPDATE_SECURITY_SHIFT_REQUEST = 'UPDATE_SECURITY_SHIFT_REQUEST';
export const REMOVE_SECURITY_SHIFT_REQUEST = 'REMOVE_SECURITY_SHIFT_REQUEST';
