export const LOAD_INITIAL_STATE = 'ACCESSORIES/LOAD_INITIAL_STATE';
export const ADD_ACCESSORY = 'ACCESSORIES/ADD_ACCESSORY';
export const UPDATE_ACCESSORY_REQUEST = 'ACCESSORIES/UPDATE_ACCESSORY_REQUEST';
export const LOAD_ACCESSORY_REQUESTS = 'ACCESSORIES/LOAD_ACCESSORY_REQUESTS';

