export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA';
export const LOAD_WTL_CARDS_DATA = 'LOAD_WTL_CARDS_DATA';
export const SET_WTL_CARDS_DATA = 'SET_WTL_CARDS_DATA';
export const INCREMENT_PAGE = 'INCREMENT_PAGE';
export const CHANGE_ACTIVE_FILTER = 'CHANGE_ACTIVE_FILTER';
export const CHANGE_CARD_NUMBER_FILTER = 'CHANGE_CARD_NUMBER_FILTER';

export const ENABLE_CARD = 'ENABLE_CARD';
export const DISABLE_CARD = 'DISABLE_CARD';
