export const COMPLETED_STEPS_CHANGED = 'COMPLETED_STEPS_CHANGED';

export const CURRENT_STEP_CHANGED = 'CURRENT_STEP_CHANGED';

export const IS_ALL_STEPS_PASSED_CHANGED = 'IS_ALL_STEPS_PASSED_CHANGED';

export const ACCESS_TOKEN_CHANGED = 'ACCESS_TOKEN_CHANGED';

export const VENUE_VALUES_CHANGED = 'VENUE_VALUES_CHANGED';

export const PAYRATE_VALUES_CHANGED = 'PAYRATE_VALUES_CHANGED';

export const STAFF_TYPE_IDS_CHANGED = 'STAFF_TYPE_IDS_CHANGED';

export const GENDER_VALUES_CHANGED = 'GENDER_VALUES_CHANGED';

export const BASIC_INFORMATION_BLOCK_VALIDATED = 'BASIC_INFORMATION_BLOCK_VALIDATED';

export const CONTACT_DETAILS_BLOCK_VALIDATED = 'CONTACT_DETAILS_BLOCK_VALIDATED';

export const VENUES_INFO_BLOCK_VALIDATED = 'VENUES_INFO_BLOCK_VALIDATED';

export const WORK_INFO_BLOCK_VALIDATED = 'WORK_INFO_BLOCK_VALIDATED';

export const AVATAR_ADDED = 'AVATAR_ADDED';

export const REGISTRATION_STEP_BACK = 'REGISTRATION_STEP_BACK';
