export const INITIAL_LOAD = 'LOAD_INITIAL_DATA';
export const ADD_SECURITY_SHIFT_REQUEST = 'ADD_SECURITY_SHIFT_REQUEST';
export const UPDATE_SECURITY_SHIFT_REQUEST = 'UPDATE_SECURITY_SHIFT_REQUEST';
export const CHANGE_WEEK_DAY = 'CHANGE_WEEK_DAY';
export const CHANGE_VENUE_FILTER = 'CHANGE_VENUE_FILTER';
