export const LOAD_DISCIPLINARIES_SUCCEED = 'LOAD_DISCIPLINARIES_SUCCEED';

export const ADD_DISCIPLINARY_SUCCEED = 'ADD_DISCIPLINARY_SUCCEED';
export const DISABLE_DISCIPLINARY_SUCCEED = 'DISABLE_DISCIPLINARY_SUCCEED';
 
