class StaffMemberPaymentPageFilter
  SHOW_ALL_STATUS_FILTER_VALUE = 'show_all'
  UNCOLLECTED_ONLY_STATUS_FILTER_VALUE = 'uncollected_only'
  LATE_ONLY_STATUS_FILTER_VALUE = 'late_only'
  STATUS_FILTER_VALUES = [SHOW_ALL_STATUS_FILTER_VALUE, UNCOLLECTED_ONLY_STATUS_FILTER_VALUE, LATE_ONLY_STATUS_FILTER_VALUE]
end
